version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    depends_on:
    - cadetapi
    - commonlistsapi
    extra_hosts:
    - "csar:10.10.200.116"
  cadetapi:
    image: ${DOCKER_REGISTRY-}cadetapi
    build:
      context: .
      dockerfile: CadetApi/Dockerfile
    depends_on:
    - db    
  commonlistsapi:
    image: ${DOCKER_REGISTRY-}commonlistsapi
    build:
      context: .
      dockerfile: CommonListsApi/Dockerfile
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server"    
  seq:    
    image: "datalust/seq"
    environment:      
        ACCEPT_EULA: "Y"   
  healthcheck:
    image: ${DOCKER_REGISTRY-}healthcheck
    build:
      context: .
      dockerfile: HealthCheck/HealthCheck/Dockerfile

