version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    depends_on:
    - cadetapi
    - coursehistory
  cadetapi:
    image: ${DOCKER_REGISTRY-}cadetapi
    build:
      context: .
      dockerfile: CadetApi/Dockerfile
    depends_on:
    - db
  coursehistory:
    image: ${DOCKER_REGISTRY-}coursehistory
    build:
      context: .
      dockerfile: CourseHistory/Dockerfile
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server"
  
