version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      # - ASPNETCORE_URLS=http://0.0.0.0:80
      # - ASPNETCORE_HTTPS_PORT=44366
    ports:
      - "5540:80"       
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  cadetapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbServer=db
      - DbPort=1433
      - DbUser=SA
      - DBPassword=Duuu988@P4w0RD!
      - Database=cadetapi
     # - ASPNETCORE_URLS=http://0.0.0.0:80
     # - ASPNETCORE_HTTPS_PORT=44359   
    ports:
      - "5541:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  commonlistsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbServer=db
      - DbPort=1433
      - DbUser=SA
      - DBPassword=Duuu988@P4w0RD!
      - Database=commonlistsapi
     # - ASPNETCORE_URLS=http://0.0.0.0:80
     # - ASPNETCORE_HTTPS_PORT=44396   
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:    
    environment:
        SA_PASSWORD: "Duuu988@P4w0RD!"
        ACCEPT_EULA: "Y"
    ports:
      - "5555:1433"

  seq:    
    environment:      
        ACCEPT_EULA: "Y"
    ports:
      - "5556:80"
      - "5341"
  healthcheck:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5557:80"

