version: '3.4'

services:
  apigateway:
    image: apigateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      # - ASPNETCORE_URLS=http://0.0.0.0:80
      # - ASPNETCORE_HTTPS_PORT=44366
    ports:
      - "6666:80"       
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    
    depends_on:
    - cadetapi
    - commonlistsapi
  cadetapi:
    image: cadetapi:latest 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbServer=db
      - DbPort=1433
      - DbUser=SA
      - DBPassword=Duuu988@P4w0RD!
      - Database=cadetapi
    # - ASPNETCORE_URLS=http://0.0.0.0:80
    # - ASPNETCORE_HTTPS_PORT=44359   
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    
    depends_on:
    - db
  commonlistsapi:
    image: commonlistsapi:latest 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbServer=db
      - DbPort=1433
      - DbUser=SA
      - DBPassword=Duuu988@P4w0RD!
      - Database=commonlistsapi
    # - ASPNETCORE_URLS=http://0.0.0.0:80
    # - ASPNETCORE_HTTPS_PORT=44396   
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro  
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server"  
    environment:
        SA_PASSWORD: "Duuu988@P4w0RD!"
        ACCEPT_EULA: "Y"
    ports:
      - "6667:1433"